Issue #183: add checking with ty.

diff --git a/data/githooks/pre-commit b/data/githooks/pre-commit
--- a/data/githooks/pre-commit
+++ b/data/githooks/pre-commit
@@ -1,6 +1,8 @@
 #!/usr/bin/env bash
 
-source .venv/bin/activate
+if [ -d ".venv" ]; then
+    source .venv/bin/activate
+fi
 
 echo "Checking code format with Ruff..."
 if ! ruff format --check; then
@@ -11,3 +13,6 @@ fi
 
 echo "Lint with Ruff..."
 ruff check || { echo "FAIL"; exit 1; }
+
+echo "Check with ty..."
+ty check || { echo "FAIL"; exit 1; }
